2015-07-17 17:02:42,843 -0    [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@15a191e] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - gaoguangjin, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:47)] 
2015-07-17 17:03:00,731 -0    [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@14b43d] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - gaoguangjin, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:47)] 
2015-07-17 17:03:25,743 -0    [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@270664] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - gaoguangjin, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:47)] 
2015-07-17 17:03:40,808 -0    [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@270664] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - gaoguangjin, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:47)] 
2015-07-17 17:04:09,604 -0    [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@1454f68] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - gaoguangjin, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:47)] 
2015-07-17 17:47:57,665 -219  [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@187514a] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhangjinyue, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:59)] 
2015-07-17 17:59:09,788 -0    [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@1f2b0dd] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - wan, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:59)] 
2015-07-17 17:59:09,808 -20   [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@1f2b0dd] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhangjinyue, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:59)] 
2015-07-17 18:00:30,563 -172  [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@187514a] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhangjinyue, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:59)] 
2015-07-17 18:00:45,429 -172  [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@904497] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhangjinyue, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:59)] 
2015-07-17 18:01:23,756 -0    [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@39b27b] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhang, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:59)] 
2015-07-17 18:01:23,772 -16   [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@39b27b] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhangjinyue, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:59)] 
2015-07-17 18:01:31,610 -156  [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@c7d960] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhangjinyue, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:59)] 
2015-07-17 18:01:45,632 -157  [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@187514a] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhangjinyue, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:61)] 
2015-07-17 18:02:40,068 -173  [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@904497] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhangjinyue, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:61)] 
2015-07-17 18:07:23,645 -156  [main] com.team.gaoguangjin.shiro.ShiroRoleDemo  ERROR - 执行错误Realm [org.apache.shiro.realm.text.IniRealm@e9e799] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - zhangjinyue, rememberMe=false]. [com.team.gaoguangjin.shiro.ShiroRoleDemo.login(ShiroRoleDemo.java:61)] 
2015-07-20 10:29:56,132 -0    [main] com.team.gaoguangjin.shiro.FirstLoginDemo  ERROR - 认证错误！Authentication failed for token submission [org.apache.shiro.authc.UsernamePasswordToken - ggj, rememberMe=false].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException). [com.team.gaoguangjin.shiro.FirstLoginDemo.login(FirstLoginDemo.java:59)] 
2015-07-22 09:20:31,668 -8810 [main] org.hibernate.engine.jdbc.spi.SqlExceptionHelper  ERROR - Cannot create PoolableConnectionFactory (Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
The Connection descriptor used by the client was:
localhost:1521:ZSORA10G
) [org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:146)] 
2015-07-22 09:49:46,295 -2818 [main] com.team.gaoguangjin.jdbc.hibernate.JunitHibernateInSpringTranstion  ERROR - ================= [com.team.gaoguangjin.jdbc.hibernate.JunitHibernateInSpringTranstion.findSpringManagerTransationQuery(JunitHibernateInSpringTranstion.java:61)] 
2015-07-22 09:49:46,357 -2880 [main] com.team.gaoguangjin.jdbc.hibernate.JunitHibernateInSpringTranstion  ERROR - For input string: "dd" [com.team.gaoguangjin.jdbc.hibernate.JunitHibernateInSpringTranstion.findSpringManagerTransationQuery(JunitHibernateInSpringTranstion.java:67)] 
2015-07-22 10:09:20,947 -11565 [main] org.hibernate.engine.jdbc.spi.SqlExceptionHelper  ERROR - ORA-01407: 无法更新 ("GAO"."TC_CLASSROOM"."ROOM_SIZE") 为 NULL
 [org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:146)] 
2015-07-23 16:40:06,605 -0    [main] com.team.gaoguangjin.javabase.exception.ExceptionThrow  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.ExceptionThrow.test(ExceptionThrow.java:26)] 
2015-07-23 16:40:20,520 -0    [main] com.team.gaoguangjin.javabase.exception.ExceptionThrow  ERROR - 父类捕获错误 [com.team.gaoguangjin.javabase.exception.ExceptionThrow.main(ExceptionThrow.java:18)] 
2015-07-23 16:46:12,027 -0    [main] com.team.gaoguangjin.javabase.exception.ExceptionThrow  ERROR - 父类捕获错误 [com.team.gaoguangjin.javabase.exception.ExceptionThrow.main(ExceptionThrow.java:19)] 
2015-07-23 16:46:30,933 -0    [main] com.team.gaoguangjin.javabase.exception.ExceptionThrow  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.ExceptionThrow.test(ExceptionThrow.java:32)] 
2015-07-23 16:47:53,506 -0    [main] com.team.gaoguangjin.javabase.exception.ExceptionThrow  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.ExceptionThrow.test(ExceptionThrow.java:39)] 
2015-07-23 16:47:53,521 -15   [main] com.team.gaoguangjin.javabase.exception.ExceptionThrow  ERROR - 父类捕获错误 [com.team.gaoguangjin.javabase.exception.ExceptionThrow.main(ExceptionThrow.java:19)] 
2015-07-23 16:53:32,896 -0    [main] com.team.gaoguangjin.javabase.exception.FinallyReturn  ERROR - 出错了！For input string: "a" [com.team.gaoguangjin.javabase.exception.FinallyReturn.getString(FinallyReturn.java:17)] 
2015-07-23 16:55:45,952 -0    [main] com.team.gaoguangjin.javabase.exception.FinallyReturn  ERROR - 出错了！For input string: "a" [com.team.gaoguangjin.javabase.exception.FinallyReturn.getString(FinallyReturn.java:18)] 
2015-07-23 16:56:06,020 -0    [main] com.team.gaoguangjin.javabase.exception.FinallyReturn  ERROR - 出错了！For input string: "a" [com.team.gaoguangjin.javabase.exception.FinallyReturn.getString(FinallyReturn.java:18)] 
2015-07-23 17:06:17,524 -0    [main] com.team.gaoguangjin.javabase.exception.ExceptionThrow  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.ExceptionThrow.test(ExceptionThrow.java:70)] 
2015-07-23 17:06:17,528 -4    [main] com.team.gaoguangjin.javabase.exception.ExceptionThrow  ERROR - 父类捕获错误 [com.team.gaoguangjin.javabase.exception.ExceptionThrow.main(ExceptionThrow.java:19)] 
2015-07-23 17:08:08,065 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:40)] 
2015-07-23 17:08:08,069 -4    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - 父类捕获错误 [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.main(ExceptionThrowTypeTwo.java:19)] 
2015-07-23 17:08:28,137 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:40)] 
2015-07-23 17:09:31,534 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:41)] 
2015-07-23 17:10:08,477 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:38)] 
2015-07-23 17:30:01,822 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:38)] 
2015-07-23 17:33:04,649 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误 [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:38)] 
2015-07-23 17:35:32,173 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 17:37:54,664 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:54)] 
2015-07-23 17:37:54,858 -194  [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 17:39:09,160 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:54)] 
2015-07-23 17:39:09,318 -158  [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 17:41:13,142 -74   [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:49)] 
2015-07-23 17:41:13,182 -114  [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:38)] 
2015-07-23 17:42:46,828 -58   [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:49)] 
2015-07-23 17:42:46,857 -87   [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test(ExceptionThrowTypeTwo.java:38)] 
2015-07-23 17:51:14,621 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test1(ExceptionThrowTypeTwo.java:37)] 
2015-07-23 17:51:14,692 -71   [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:48)] 
2015-07-23 18:00:00,956 -7    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test1(ExceptionThrowTypeTwo.java:32)] 
2015-07-23 18:00:00,958 -9    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 18:00:15,322 -6    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test1(ExceptionThrowTypeTwo.java:32)] 
2015-07-23 18:00:15,324 -8    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 18:01:26,015 -7    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test1(ExceptionThrowTypeTwo.java:32)] 
2015-07-23 18:01:26,017 -9    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 18:01:48,605 -8    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test1(ExceptionThrowTypeTwo.java:32)] 
2015-07-23 18:01:48,607 -10   [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 18:07:49,569 -6    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test1(ExceptionThrowTypeTwo.java:32)] 
2015-07-23 18:07:49,570 -7    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 18:07:57,774 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 18:08:06,122 -6    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test1(ExceptionThrowTypeTwo.java:32)] 
2015-07-23 18:08:06,124 -8    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 18:08:36,675 -0    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test3():aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test3(ExceptionThrowTypeTwo.java:52)] 
2015-07-23 18:08:36,682 -7    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - catch错误aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test1(ExceptionThrowTypeTwo.java:32)] 
2015-07-23 18:08:36,684 -9    [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test2()：aaa (系统找不到指定的文件。) [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test2(ExceptionThrowTypeTwo.java:43)] 
2015-07-23 18:08:36,685 -10   [main] com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo  ERROR - test5 catch错误For input string: "a" [com.team.gaoguangjin.javabase.exception.throwexception.ExceptionThrowTypeTwo.test6(ExceptionThrowTypeTwo.java:70)] 
2015-07-27 13:26:41,112 -22   [main] com.team.gaoguangjin.shiro.TestSecond  ERROR - 认证失败：null [com.team.gaoguangjin.shiro.TestSecond.test(TestSecond.java:36)] 
2015-07-28 17:04:33,910 -10861 [main] com.alibaba.druid.pool.DruidDataSource  ERROR - init datasource error [com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:612)] 
java.sql.SQLException: ORA-01033: ORACLE initialization or shutdown in progress

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:283)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:278)
	at oracle.jdbc.driver.T4CTTIoauthenticate.receiveOsesskey(T4CTTIoauthenticate.java:288)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:357)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:414)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:148)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:211)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1360)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1414)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:602)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1681)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:175)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:609)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:125)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:100)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:250)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContextInternal(CacheAwareContextLoaderDelegate.java:64)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:91)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:101)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:331)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:213)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:290)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:292)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
2015-07-28 17:04:33,956 -10907 [main] com.alibaba.druid.pool.DruidDataSource  ERROR - dataSource init error [com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:629)] 
java.sql.SQLException: ORA-01033: ORACLE initialization or shutdown in progress

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:283)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:278)
	at oracle.jdbc.driver.T4CTTIoauthenticate.receiveOsesskey(T4CTTIoauthenticate.java:288)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:357)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:414)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:148)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:211)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1360)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1414)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:602)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1681)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:175)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:609)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:125)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:100)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:250)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContextInternal(CacheAwareContextLoaderDelegate.java:64)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:91)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:101)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:331)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:213)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:290)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:292)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
2015-07-28 17:04:33,956 -10907 [main] org.springframework.test.context.TestContextManager  ERROR - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@1ad25b6] to prepare test instance [com.team.gaoguangjin.jdbc.mybatis.springxml.JunitTestMyBatis@86ef5c] [org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:334)] 
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:101)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:331)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:213)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:290)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:292)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.mybatis.spring.mapper.MapperScannerConfigurer#0' defined in class path resource [jdbcconfig/mybatisconfig/spring/springmybatisjdbc.xml]: Cannot resolve reference to bean 'sqlSessionFactory' while setting bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [jdbcconfig/mybatisconfig/spring/springmybatisjdbc.xml]: Cannot resolve reference to bean 'dataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [jdbcconfig/mybatisconfig/spring/springmybatisjdbc.xml]: Invocation of init method failed; nested exception is java.sql.SQLException: ORA-01033: ORACLE initialization or shutdown in progress

	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:336)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:175)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:609)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:125)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:100)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:250)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContextInternal(CacheAwareContextLoaderDelegate.java:64)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:91)
	... 25 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [jdbcconfig/mybatisconfig/spring/springmybatisjdbc.xml]: Cannot resolve reference to bean 'dataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [jdbcconfig/mybatisconfig/spring/springmybatisjdbc.xml]: Invocation of init method failed; nested exception is java.sql.SQLException: ORA-01033: ORACLE initialization or shutdown in progress

	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:336)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	... 43 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [jdbcconfig/mybatisconfig/spring/springmybatisjdbc.xml]: Invocation of init method failed; nested exception is java.sql.SQLException: ORA-01033: ORACLE initialization or shutdown in progress

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	... 53 more
Caused by: java.sql.SQLException: ORA-01033: ORACLE initialization or shutdown in progress

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:283)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:278)
	at oracle.jdbc.driver.T4CTTIoauthenticate.receiveOsesskey(T4CTTIoauthenticate.java:288)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:357)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:414)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:801)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:148)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:211)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1360)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1414)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:602)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1681)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
	... 60 more
